Added Pagination
gsvamsi18/SampleProject pull request #42
Opened 2022-12-23 02:55 UTC by gsvamsiBZ

2022-12-23 02:56 UTC, gsvamsiBZ commented
![image](https://user-images.githubusercontent.com/108448901/209261761-b4aa313a-21fd-4d88-9e00-22c72b30b7f8.png)
![image](https://user-images.githubusercontent.com/108448901/209261807-0d837319-4ad1-43be-b4df-af9b89bfaffb.png)

2022-12-24 03:26 UTC, Siddhartha-bethi approved these changes

2022-12-24 05:02 UTC, gsvamsi18 commented
create a new function to getRecordsWithPagination and update getallrecords to give all records

2022-12-24 13:42 UTC, Karthik-184 requested changes

2022-12-24 14:25 UTC, Karthik-184 approved these changes

2022-12-24 14:26 UTC, merged